name: "test issue copy"
on:
    issue_comment:
        types: [created]
jobs:
    copy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ./tools/issue-copy-action-0.2.0
              with:
                keyword: "/copy"
                targetRepository: Orange-hayashi/test1
                githubToken: ${{ secrets.GITHUB_TOKEN }}
                contentOfNewIssue: 'prefix of newly created issue'
